// This file will be auto-generated by Supabase CLI
// For now, we'll create basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          full_name: string
          email: string
          age_verified: boolean
          age_verified_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name: string
          email: string
          age_verified?: boolean
          age_verified_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          age_verified?: boolean
          age_verified_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      teams: {
        Row: {
          id: string
          owner_id: string
          name: string
          sport: string
          season: string | null
          team_colors: Json
          logo_url: string | null
          privacy_settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          sport: string
          season?: string | null
          team_colors?: Json
          logo_url?: string | null
          privacy_settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          sport?: string
          season?: string | null
          team_colors?: Json
          logo_url?: string | null
          privacy_settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
      children: {
        Row: {
          id: string
          team_id: string
          first_name: string
          jersey_number: string | null
          position: string | null
          birth_year: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          team_id: string
          first_name: string
          jersey_number?: string | null
          position?: string | null
          birth_year?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          team_id?: string
          first_name?: string
          jersey_number?: string | null
          position?: string | null
          birth_year?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      photos: {
        Row: {
          id: string
          team_id: string
          child_id: string | null
          original_url: string
          processed_url: string | null
          thumbnail_url: string | null
          quality_score: number | null
          metadata: Json
          processing_status: string
          created_at: string
          delete_at: string
        }
        Insert: {
          id?: string
          team_id: string
          child_id?: string | null
          original_url: string
          processed_url?: string | null
          thumbnail_url?: string | null
          quality_score?: number | null
          metadata?: Json
          processing_status?: string
          created_at?: string
          delete_at?: string
        }
        Update: {
          id?: string
          team_id?: string
          child_id?: string | null
          original_url?: string
          processed_url?: string | null
          thumbnail_url?: string | null
          quality_score?: number | null
          metadata?: Json
          processing_status?: string
          created_at?: string
          delete_at?: string
        }
      }
      card_designs: {
        Row: {
          id: string
          team_id: string
          child_id: string
          photo_id: string | null
          template_id: string
          customization: Json
          front_design: Json
          back_design: Json
          bio_text: string | null
          stats: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          team_id: string
          child_id: string
          photo_id?: string | null
          template_id: string
          customization?: Json
          front_design: Json
          back_design: Json
          bio_text?: string | null
          stats?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          team_id?: string
          child_id?: string
          photo_id?: string | null
          template_id?: string
          customization?: Json
          front_design?: Json
          back_design?: Json
          bio_text?: string | null
          stats?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          user_id: string
          team_id: string | null
          status: string
          items: Json
          subtotal: number
          tax: number | null
          shipping: number | null
          total: number
          stripe_payment_intent_id: string | null
          stripe_session_id: string | null
          shipping_address: Json | null
          tracking_number: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          team_id?: string | null
          status?: string
          items: Json
          subtotal: number
          tax?: number | null
          shipping?: number | null
          total: number
          stripe_payment_intent_id?: string | null
          stripe_session_id?: string | null
          shipping_address?: Json | null
          tracking_number?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          team_id?: string | null
          status?: string
          items?: Json
          subtotal?: number
          tax?: number | null
          shipping?: number | null
          total?: number
          stripe_payment_intent_id?: string | null
          stripe_session_id?: string | null
          shipping_address?: Json | null
          tracking_number?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      consent_log: {
        Row: {
          id: string
          parent_id: string
          child_id: string
          consent_type: string
          granted: boolean
          ip_address: string | null
          user_agent: string | null
          timestamp: string
        }
        Insert: {
          id?: string
          parent_id: string
          child_id: string
          consent_type: string
          granted: boolean
          ip_address?: string | null
          user_agent?: string | null
          timestamp?: string
        }
        Update: {
          id?: string
          parent_id?: string
          child_id?: string
          consent_type?: string
          granted?: boolean
          ip_address?: string | null
          user_agent?: string | null
          timestamp?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Helper types
export type User = Database['public']['Tables']['users']['Row'];
export type Team = Database['public']['Tables']['teams']['Row'];
export type Child = Database['public']['Tables']['children']['Row'];
export type Photo = Database['public']['Tables']['photos']['Row'];
export type CardDesign = Database['public']['Tables']['card_designs']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type ConsentLog = Database['public']['Tables']['consent_log']['Row'];