# Netlify Configuration for Librarian LLM
# This app lives in: librarian-llm/

[build]
  # Base directory where the app lives
  base = "librarian-llm"

  # Build command to run
  command = "npm run build"

  # Directory where built files are output (relative to base)
  publish = "dist"

  # Netlify Functions directory
  functions = "netlify/functions"

  # Node version to use
  [build.environment]
    NODE_VERSION = "20"

# SPA (Single Page Application) Redirect Rule
# This ensures React Router works properly on direct URL access
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Set cache headers for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
