/**
 * TOMO — Technique Tree Type Definitions
 *
 * Hierarchical BJJ technique taxonomy organized by position.
 * Each position branches into offense, defense, and neutral.
 *
 * Data source: 14 CSV files in docs/domain-knowledge/bjj-techniques/bjj_library/
 * Generated by: scripts/build-technique-tree.ts
 */

// ===========================================
// CORE ENUMS
// ===========================================

/** Where you are on the mat */
export type PositionId =
  | 'closed_guard'
  | 'half_guard'
  | 'open_guard'
  | 'mount'
  | 'side_control'
  | 'back_control'
  | 'knee_on_belly'
  | 'north_south'
  | 'turtle'
  | 'standing'
  | 'leg_entanglements'
  | 'guard_passing';

/** Your perspective — are you on top, bottom, standing, or in a scramble? */
export type Perspective = 'top' | 'bottom' | 'standing' | 'neutral';

/** What the technique does */
export type TechniqueType =
  | 'submission'
  | 'sweep'
  | 'pass'
  | 'escape'
  | 'control'
  | 'transition'
  | 'entry'
  | 'takedown'
  | 'defense';

/** Which branch of the tree a technique belongs to */
export type Branch = 'offense' | 'defense' | 'neutral';

/** Belt level required */
export type BeltLevel =
  | 'white'
  | 'blue'
  | 'purple'
  | 'brown'
  | 'all_belts'
  | 'blue_and_above'
  | 'brown_black_only'
  | 'brown_black_nogi_only';

/** Gi/No-Gi applicability */
export type GiNogi = 'gi' | 'nogi' | 'both';

// ===========================================
// TECHNIQUE NODE
// ===========================================

/** A single technique in the tree */
export interface Technique {
  /** Unique ID from CSV (e.g., CG_001, SM_005) */
  id: string;
  /** Primary name */
  name: string;
  /** Alternate names / aliases (pipe-separated in CSV) */
  alternateNames: string[];
  /** Portuguese/Japanese name */
  traditionalName: string | null;
  /** What this technique does */
  type: TechniqueType;
  /** More specific category (e.g., "choke", "armlock", "underhook") */
  subcategory: string;
  /** Which branch: offense, defense, or neutral */
  branch: Branch;
  /** Minimum belt level */
  beltLevel: BeltLevel;
  /** Gi, No-Gi, or both */
  giNogi: GiNogi;
  /** IBJJF legality */
  ibjjfLegal: string;
  /** Short description */
  description: string;
  /** Key execution points */
  keyPoints: string[];
  /** Common mistakes */
  commonMistakes: string[];
  /** IDs of related techniques (for chains/flows) */
  relatedIds: string[];
  /** IDs of counter techniques (for defense study) */
  counterIds: string[];
  /**
   * Position IDs where this technique can be executed.
   * Primary position is [0], others are secondary.
   */
  positionIds: PositionId[];
}

// ===========================================
// POSITION NODE
// ===========================================

/** A position in the tree — the top-level grouping */
export interface Position {
  /** Machine ID */
  id: PositionId;
  /** Display name */
  name: string;
  /** Short description */
  description: string;
  /** Your perspective when in this position */
  perspective: Perspective;
  /** CSV ID prefix (e.g., "CG" for closed guard) */
  csvPrefix: string;
  /** Techniques organized by branch */
  branches: {
    offense: Technique[];
    defense: Technique[];
    neutral: Technique[];
  };
}

// ===========================================
// TECHNIQUE TREE (ROOT)
// ===========================================

/** The complete technique tree */
export interface TechniqueTree {
  /** Version for cache invalidation */
  version: string;
  /** All positions */
  positions: Position[];
  /** Flat lookup: technique ID → Technique (for quick access) */
  index: Record<string, Technique>;
  /** Stats */
  stats: {
    totalTechniques: number;
    totalPositions: number;
    byBelt: Record<string, number>;
    byType: Record<string, number>;
    byBranch: Record<string, number>;
  };
}

// ===========================================
// QUERY HELPERS (types only — impl in tree file)
// ===========================================

/** Filter options for browsing the tree */
export interface TechniqueFilter {
  positionId?: PositionId;
  branch?: Branch;
  type?: TechniqueType;
  beltLevel?: BeltLevel;
  giNogi?: GiNogi;
  search?: string;
}
